### ISSUE TITLE
How to serialize a relationship request (no attributes)

### ISSUE THREAD

**Issue by sarus** [SeyZ/jsonapi-serializer#40]
I'm trying to create the response to a relationship URL such as

```
/articles/1/relationships/tags
```

According to the JSON API 1.0 spec (http://jsonapi.org/format/#fetching-relationships) the response should be:

```
{
  "links": {
    "self": "/articles/1/relationships/tags",
    "related": "/articles/1/tags"
  },
  "data": [
    { "type": "tags", "id": "2" },
    { "type": "tags", "id": "3" }
  ]
}
```

My data is in the format:

```
[
  {
    "id": 2
  },
  {
    "id": 3
  }
]
```

How can I serialize this using jsonapi-serializer?

I tried something like this:

```
                var json = new JSONAPISerializer('tags', result.rows, {
                    ref: true,
                    included: false,
                    topLevelLinks: {
                        self: "/articles/1/relationships/tags",
                        related: "/articles/1/tags"
                    },
                    attributes: []
                });
```

but that results in an empty `attributes` object being added to the data

```
{
  "links": {
    "self": "/articles/1/relationships/tags",
    "related": "/articles/1/tags"
  },
  "data": [
    { "type": "tags", "id": "2", "attributes":{} },
    { "type": "tags", "id": "3", "attributes":{} }
  ]
}
```

If I don't specify attributes as an empty array then the serializer crashes with an indexOf error.

```
TypeError: Cannot read property 'indexOf' of undefined
        at isAttrAllowed (/workspace/server/node_modules/jsonapi-serializer/lib/serializer-utils.js:89:22)
        at /workspace/server/node_modules/jsonapi-serializer/lib/serializer-utils.js:204:12
```

**Comment by SeyZ** [comment]
Good point! It's definitively an issue!

**Comment by Aurelsicoko** [comment]
I still have this issue. Maybe this version isn't published on npm?

**Comment by two7sclash** [comment]
still have this issue!

**Comment by geoffreyLB** [comment]
still have the same issue ``attributes: []`` will not return all default attributes of my data.
